import { MigrationInterface, QueryRunner } from "typeorm";

export class ModelISet0101741877989301 implements MigrationInterface {
    name = 'ModelISet0101741877989301'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`Auditoria\` DROP FOREIGN KEY \`FK_1f4e9039fc5f64667e4693d2742\``);
        await queryRunner.query(`ALTER TABLE \`Cidade\` CHANGE \`estado\` \`Estado\` text NOT NULL COMMENT 'Nome do estado onde a cidade está localizada'`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` COMMENT 'Subdivisões de agregadores'`);
        await queryRunner.query(`ALTER TABLE \`Agregador\` COMMENT 'Agregadores de locais de atendimento'`);
        await queryRunner.query(`ALTER TABLE \`Cidade\` COMMENT 'Cidades e estados cadastrados'`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` COMMENT 'Credenciais de login dos cidadãos'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` COMMENT 'Monitores de chamada de senha'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` COMMENT 'Dispositivos autorizados a acessar o sistema'`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` COMMENT 'Avaliações dos cidadãos sobre atendimentos'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` COMMENT 'Ações de atendimento vinculadas a serviços'`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` COMMENT 'Guichês de atendimento disponíveis'`);
        await queryRunner.query(`ALTER TABLE \`Local\` COMMENT 'Locais de atendimento de serviços'`);
        await queryRunner.query(`ALTER TABLE \`Rotulo\` COMMENT 'Rótulos para padronização de pré-requisitos'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` COMMENT 'Pré-requisitos dos serviços oferecidos'`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` COMMENT 'Serviços disponibilizados para atendimento'`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` COMMENT 'Credenciais de login dos usuários do sistema'`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` COMMENT 'Registros de auditoria de atividades do sistema'`);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` COMMENT 'Configurações globais do sistema'`);
        await queryRunner.query(`CREATE TABLE \`Direcionamento\` (\`ID\` int NOT NULL, \`status\` tinyint NOT NULL COMMENT 'Status: 0 - indisponível, 1 - disponível' DEFAULT '1', \`tipo\` int NOT NULL COMMENT 'Tipo: 1 - triagem, 2 - atendimento' DEFAULT '1', \`rotulo\` varchar(4) NOT NULL COMMENT 'Rótulo do direcionamento (ex: "TRI-")', \`Guiche_ID\` int NOT NULL, \`Servico_ID\` int NOT NULL, PRIMARY KEY (\`ID\`)) ENGINE=InnoDB COMMENT="Direcionamento de serviços para guichês"`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` DROP COLUMN \`auth0\``);
        await queryRunner.query(`ALTER TABLE \`Guiche\` DROP COLUMN \`numero\``);
        await queryRunner.query(`ALTER TABLE \`Servico\` DROP COLUMN \`identificacao\``);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` DROP COLUMN \`usuarioRefID\``);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` DROP COLUMN \`ID\``);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` ADD \`Auth0\` text NULL COMMENT 'Dados de autenticação externa (JSON)'`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` ADD \`identificacao\` int(3) ZEROFILL NOT NULL COMMENT 'Número do guichê (3 dígitos zerofill)'`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` ADD \`disponibilidade\` int NOT NULL COMMENT 'Disponibilidade: 0 - fora, 1 - aguardando, 2 - atendendo, 3 - suspenso' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` ADD \`Usuario_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Local\` DROP FOREIGN KEY \`FK_ce835d1dc03811939b677a4d1f1\``);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` DROP FOREIGN KEY \`FK_46d9d6f67f5d0c5bf38cbd5099f\``);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - desativado, 1 - ativado' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` CHANGE \`nome\` \`nome\` text NOT NULL COMMENT 'Nome do sub-agregador'`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` CHANGE \`Agregador_ID\` \`Agregador_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Local\` DROP FOREIGN KEY \`FK_6c248ba5f55b09a1d1abf98e0a7\``);
        await queryRunner.query(`ALTER TABLE \`Agregador\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Agregador\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - desativado, 1 - ativado'`);
        await queryRunner.query(`ALTER TABLE \`Agregador\` CHANGE \`nome\` \`nome\` varchar(45) NOT NULL COMMENT 'Nome do agregador'`);
        await queryRunner.query(`ALTER TABLE \`Local\` DROP FOREIGN KEY \`FK_333efabf632ebf13f53bf8299b0\``);
        await queryRunner.query(`ALTER TABLE \`Cidade\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Cidade\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - inativo, 1 - ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Cidade\` CHANGE \`Estado\` \`Estado\` text NOT NULL COMMENT 'Nome do estado'`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` DROP FOREIGN KEY \`FK_fb673fb22d54f1dd99298f0773f\``);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` CHANGE \`Cidadao_ID\` \`Cidadao_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` CHANGE \`CPF\` \`CPF\` varchar(32) NOT NULL COMMENT 'CPF único (com pontuação)'`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` CHANGE \`senha\` \`senha\` varchar(32) NOT NULL COMMENT 'Senha codificada. "Default" requer atualização no primeiro acesso.' DEFAULT 'Default'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` DROP FOREIGN KEY \`FK_34ced1e1560b9eace850e23a424\``);
        await queryRunner.query(`ALTER TABLE \`Monitor\` DROP FOREIGN KEY \`FK_88bacd5f4eade404c9f9db563f2\``);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`Dispositivo_ID\` \`Dispositivo_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Inativo, 1 - Ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`rotulo\` \`rotulo\` varchar(255) NULL COMMENT 'Rótulo para identificação do monitor'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`dataCadastro\` \`dataCadastro\` timestamp NOT NULL COMMENT 'Data de cadastro do monitor' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` DROP COLUMN \`guiches\``);
        await queryRunner.query(`ALTER TABLE \`Monitor\` ADD \`guiches\` json NULL COMMENT 'Guichês vinculados (IDs em formato JSON)'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` DROP FOREIGN KEY \`FK_30ab90c85f6a53f6f733c5b05a3\``);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` DROP FOREIGN KEY \`FK_818e77e86b5018e0e480353ba8a\``);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - inativo, 1 - ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`identificacao\` \`identificacao\` varchar(45) NOT NULL COMMENT 'Hash de identificação do dispositivo'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`rotulo\` \`rotulo\` varchar(45) NOT NULL COMMENT 'Nome amigável do dispositivo' DEFAULT 'Rótulo que identifica o dispositivo'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`Cidadao_ID\` \`Cidadao_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` DROP FOREIGN KEY \`FK_94136eed977b8bc08033379c198\``);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`nome\` \`nome\` text NOT NULL COMMENT 'Nome do cidadão'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - inativo, 1 - ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`cidade\` \`cidade\` text NULL COMMENT 'Cidade de residência'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`telefone\` \`telefone\` text NULL COMMENT 'Telefones (separados por ";")'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`email\` \`email\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`dataHoraCadastro\` \`dataHoraCadastro\` timestamp NOT NULL COMMENT 'Data/hora do cadastro' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`prioridade\` \`prioridade\` int(1) NULL COMMENT 'Prioridade: NULL - sem, 1 - idoso, 2 - patologia'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`dataNascimento\` \`dataNascimento\` date NULL COMMENT 'Data de nascimento (opcional)'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`ultimoAcesso\` \`ultimoAcesso\` timestamp NOT NULL COMMENT 'Último acesso ao sistema' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` DROP FOREIGN KEY \`FK_d9b15735f8ff9e2510edca00bc2\``);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` CHANGE \`Atendimento_ID\` \`Atendimento_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` CHANGE \`estrelas\` \`estrelas\` int(1) NOT NULL COMMENT 'Avaliação em estrelas: 1 (péssimo) a 5 (perfeito)'`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` CHANGE \`comentario\` \`comentario\` text NULL COMMENT 'Comentário opcional do cidadão'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` DROP FOREIGN KEY \`FK_c49578aa0e6a82d161af1a7bc6f\``);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` DROP FOREIGN KEY \`FK_25a50daf6603557150f59e9ef56\``);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` DROP FOREIGN KEY \`FK_90d296b374d2947bf494499a275\``);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`status\` \`status\` int NOT NULL COMMENT 'Status: 0-Não finalizado, 1-Em atendimento, 2-Finalizado, 3-Aguardando retorno' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`tipo\` \`tipo\` int NOT NULL COMMENT 'Tipo: 0-Comum, 1-Prioridade, 2-Retorno, 3-Retorno com prioridade'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`senha\` \`senha\` varchar(9) NOT NULL COMMENT 'Senha no formato "LLL-000"'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`dataCadastro\` \`dataCadastro\` timestamp NOT NULL COMMENT 'Data de cadastro do atendimento' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`dataFinal\` \`dataFinal\` timestamp NULL COMMENT 'Data de conclusão/finalização'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`Cidadao_ID\` \`Cidadao_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`Local_ID\` \`Local_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Acao\` DROP FOREIGN KEY \`FK_4a0c0eb22196d5e94570f8d67f8\``);
        await queryRunner.query(`ALTER TABLE \`Acao\` DROP FOREIGN KEY \`FK_6f6b95908be2047467f5901a39c\``);
        await queryRunner.query(`ALTER TABLE \`Acao\` DROP FOREIGN KEY \`FK_81d8aaa180f951427e6f7a53c44\``);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`status\` \`status\` int NOT NULL COMMENT 'Status: 0 - aguardando, 1 - em atendimento, 2 - finalizado, 3 - adiado' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`posicao\` \`posicao\` int NOT NULL COMMENT 'Posição na fila de atendimento'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`data\` \`data\` date NULL COMMENT 'Data do atendimento'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`horaInicio\` \`horaInicio\` time NULL COMMENT 'Hora de início do atendimento'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`horaFim\` \`horaFim\` time NULL COMMENT 'Hora de término do atendimento'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`anotacao\` \`anotacao\` text NULL COMMENT 'Anotações do atendente'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`Atendimento_ID\` \`Atendimento_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`Guiche_ID\` \`Guiche_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`Servico_ID\` \`Servico_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` DROP FOREIGN KEY \`FK_c933344d00d6b16fcf1566b5a84\``);
        await queryRunner.query(`ALTER TABLE \`Guiche\` DROP FOREIGN KEY \`FK_c6b5861984a164f66f44c077a11\``);
        await queryRunner.query(`ALTER TABLE \`Guiche\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - indisponível, 1 - disponível' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` CHANGE \`Local_ID\` \`Local_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` DROP FOREIGN KEY \`FK_291c34c971b812fd3399c25c18e\``);
        await queryRunner.query(`ALTER TABLE \`Local\` DROP FOREIGN KEY \`FK_43868f1ccf68d30c744e665b82a\``);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - desativado, 1 - ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`endereco\` \`endereco\` text NULL COMMENT 'Endereço físico do local'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`linkMaps\` \`linkMaps\` text NULL COMMENT 'Link do Google Maps'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`telefone\` \`telefone\` text NULL COMMENT 'Telefones (separados por ";")'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`CEP\` \`CEP\` varchar(15) NULL COMMENT 'CEP do local'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`Orgao_ID\` \`Orgao_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`Agregador_ID\` \`Agregador_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`SubAgregado_ID\` \`SubAgregado_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`Cidade_ID\` \`Cidade_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` DROP FOREIGN KEY \`FK_fb733acbf5a893769678e192f55\``);
        await queryRunner.query(`ALTER TABLE \`Rotulo\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Rotulo\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - inativo, 1 - ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Rotulo\` CHANGE \`rotulo\` \`rotulo\` varchar(255) NOT NULL COMMENT 'Título do rótulo'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` DROP FOREIGN KEY \`FK_153d5c9555c9e12c20a41f8075e\``);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - indisponível, 1 - disponível' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`conteudo\` \`conteudo\` text NOT NULL COMMENT 'Descrição do pré-requisito'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`Conteudo_ID\` \`Conteudo_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`Rotulo_ID\` \`Rotulo_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` DROP FOREIGN KEY \`FK_595a32b60dae4f548fe15572791\``);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - indisponível, 1 - disponível' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`descricao\` \`descricao\` text NOT NULL COMMENT 'Descrição detalhada do serviço'`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`Servico_ID\` \`Servico_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`Local_ID\` \`Local_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Servico\` DROP FOREIGN KEY \`FK_41dcbbc17f020c41b5b4d1a4e23\``);
        await queryRunner.query(`ALTER TABLE \`Servico\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Servico\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - desativado, 1 - disponível'`);
        await queryRunner.query(`ALTER TABLE \`Servico\` CHANGE \`titulo\` \`titulo\` varchar(255) NOT NULL COMMENT 'Título do serviço'`);
        await queryRunner.query(`ALTER TABLE \`Servico\` CHANGE \`Orgao_ID\` \`Orgao_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` DROP FOREIGN KEY \`FK_ac16fdcbf57da5794c6e221b44a\``);
        await queryRunner.query(`ALTER TABLE \`Orgao\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Orgao\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status atual do órgão: 0 - inativo, 1 - ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Orgao\` CHANGE \`nome\` \`nome\` varchar(45) NOT NULL COMMENT 'Nome do órgão'`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` DROP FOREIGN KEY \`FK_2edf88b662ccf08e1e3d23bd629\``);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` CHANGE \`usuario\` \`usuario\` text NOT NULL COMMENT 'Nome de usuário único'`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` CHANGE \`senha\` \`senha\` text NOT NULL COMMENT 'Senha codificada'`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` CHANGE \`codigo\` \`codigo\` varchar(45) NOT NULL COMMENT 'Código do evento (formato: CÓDIGO-JSON-IP-TIPO_ATOR-GUICHE-...)'`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` CHANGE \`timestamp\` \`timestamp\` timestamp NOT NULL COMMENT 'Data/hora do evento auditado' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - inativo, 1 - ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`disponibilidade\` \`disponibilidade\` tinyint NOT NULL COMMENT 'Disponibilidade: 0 - indisponível, 1 - disponível' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`nivel\` \`nivel\` int NOT NULL COMMENT 'Nível de acesso (0-4). 0 = Administrador'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`nome\` \`nome\` varchar(45) NOT NULL COMMENT 'Nome real do usuário'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`Orgao_ID\` \`Orgao_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` CHANGE \`qtdSenhasExibidasNoMonitor\` \`qtdSenhasExibidasNoMonitor\` int(2) NOT NULL COMMENT 'Quantidade de senhas exibidas nos monitores'`);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` ADD PRIMARY KEY (\`qtdSenhasExibidasNoMonitor\`)`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` ADD CONSTRAINT \`FK_46d9d6f67f5d0c5bf38cbd5099f\` FOREIGN KEY (\`Agregador_ID\`) REFERENCES \`Agregador\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` ADD CONSTRAINT \`FK_fb673fb22d54f1dd99298f0773f\` FOREIGN KEY (\`Cidadao_ID\`) REFERENCES \`Cidadao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` ADD CONSTRAINT \`FK_88bacd5f4eade404c9f9db563f2\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` ADD CONSTRAINT \`FK_34ced1e1560b9eace850e23a424\` FOREIGN KEY (\`Dispositivo_ID\`) REFERENCES \`Dispositivo\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` ADD CONSTRAINT \`FK_30ab90c85f6a53f6f733c5b05a3\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` ADD CONSTRAINT \`FK_818e77e86b5018e0e480353ba8a\` FOREIGN KEY (\`Cidadao_ID\`) REFERENCES \`Cidadao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` ADD CONSTRAINT \`FK_d9b15735f8ff9e2510edca00bc2\` FOREIGN KEY (\`Atendimento_ID\`) REFERENCES \`Atendimento\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` ADD CONSTRAINT \`FK_94136eed977b8bc08033379c198\` FOREIGN KEY (\`Cidadao_ID\`) REFERENCES \`Cidadao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` ADD CONSTRAINT \`FK_25a50daf6603557150f59e9ef56\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` ADD CONSTRAINT \`FK_90d296b374d2947bf494499a275\` FOREIGN KEY (\`Local_ID\`) REFERENCES \`Local\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Acao\` ADD CONSTRAINT \`FK_c49578aa0e6a82d161af1a7bc6f\` FOREIGN KEY (\`Atendimento_ID\`) REFERENCES \`Atendimento\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Acao\` ADD CONSTRAINT \`FK_4a0c0eb22196d5e94570f8d67f8\` FOREIGN KEY (\`Guiche_ID\`) REFERENCES \`Guiche\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Acao\` ADD CONSTRAINT \`FK_6f6b95908be2047467f5901a39c\` FOREIGN KEY (\`Servico_ID\`) REFERENCES \`Servico\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Acao\` ADD CONSTRAINT \`FK_81d8aaa180f951427e6f7a53c44\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Direcionamento\` ADD CONSTRAINT \`FK_85c3689ba2fc5ef327b0a868ad0\` FOREIGN KEY (\`Guiche_ID\`) REFERENCES \`Guiche\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Direcionamento\` ADD CONSTRAINT \`FK_7263145c2f094b22627c24dd105\` FOREIGN KEY (\`Servico_ID\`) REFERENCES \`Servico\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` ADD CONSTRAINT \`FK_c933344d00d6b16fcf1566b5a84\` FOREIGN KEY (\`Local_ID\`) REFERENCES \`Local\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` ADD CONSTRAINT \`FK_c6b5861984a164f66f44c077a11\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Local\` ADD CONSTRAINT \`FK_43868f1ccf68d30c744e665b82a\` FOREIGN KEY (\`Orgao_ID\`) REFERENCES \`Orgao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Local\` ADD CONSTRAINT \`FK_6c248ba5f55b09a1d1abf98e0a7\` FOREIGN KEY (\`Agregador_ID\`) REFERENCES \`Agregador\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Local\` ADD CONSTRAINT \`FK_ce835d1dc03811939b677a4d1f1\` FOREIGN KEY (\`SubAgregado_ID\`) REFERENCES \`SubAgregado\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Local\` ADD CONSTRAINT \`FK_333efabf632ebf13f53bf8299b0\` FOREIGN KEY (\`Cidade_ID\`) REFERENCES \`Cidade\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` ADD CONSTRAINT \`FK_153d5c9555c9e12c20a41f8075e\` FOREIGN KEY (\`Conteudo_ID\`) REFERENCES \`Conteudo\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` ADD CONSTRAINT \`FK_fb733acbf5a893769678e192f55\` FOREIGN KEY (\`Rotulo_ID\`) REFERENCES \`Rotulo\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` ADD CONSTRAINT \`FK_595a32b60dae4f548fe15572791\` FOREIGN KEY (\`Servico_ID\`) REFERENCES \`Servico\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` ADD CONSTRAINT \`FK_291c34c971b812fd3399c25c18e\` FOREIGN KEY (\`Local_ID\`) REFERENCES \`Local\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Servico\` ADD CONSTRAINT \`FK_41dcbbc17f020c41b5b4d1a4e23\` FOREIGN KEY (\`Orgao_ID\`) REFERENCES \`Orgao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` ADD CONSTRAINT \`FK_2edf88b662ccf08e1e3d23bd629\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` ADD CONSTRAINT \`FK_56c0a4f6c36f1b44d11e0200338\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` ADD CONSTRAINT \`FK_ac16fdcbf57da5794c6e221b44a\` FOREIGN KEY (\`Orgao_ID\`) REFERENCES \`Orgao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`Usuario\` DROP FOREIGN KEY \`FK_ac16fdcbf57da5794c6e221b44a\``);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` DROP FOREIGN KEY \`FK_56c0a4f6c36f1b44d11e0200338\``);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` DROP FOREIGN KEY \`FK_2edf88b662ccf08e1e3d23bd629\``);
        await queryRunner.query(`ALTER TABLE \`Servico\` DROP FOREIGN KEY \`FK_41dcbbc17f020c41b5b4d1a4e23\``);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` DROP FOREIGN KEY \`FK_291c34c971b812fd3399c25c18e\``);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` DROP FOREIGN KEY \`FK_595a32b60dae4f548fe15572791\``);
        await queryRunner.query(`ALTER TABLE \`Requisito\` DROP FOREIGN KEY \`FK_fb733acbf5a893769678e192f55\``);
        await queryRunner.query(`ALTER TABLE \`Requisito\` DROP FOREIGN KEY \`FK_153d5c9555c9e12c20a41f8075e\``);
        await queryRunner.query(`ALTER TABLE \`Local\` DROP FOREIGN KEY \`FK_333efabf632ebf13f53bf8299b0\``);
        await queryRunner.query(`ALTER TABLE \`Local\` DROP FOREIGN KEY \`FK_ce835d1dc03811939b677a4d1f1\``);
        await queryRunner.query(`ALTER TABLE \`Local\` DROP FOREIGN KEY \`FK_6c248ba5f55b09a1d1abf98e0a7\``);
        await queryRunner.query(`ALTER TABLE \`Local\` DROP FOREIGN KEY \`FK_43868f1ccf68d30c744e665b82a\``);
        await queryRunner.query(`ALTER TABLE \`Guiche\` DROP FOREIGN KEY \`FK_c6b5861984a164f66f44c077a11\``);
        await queryRunner.query(`ALTER TABLE \`Guiche\` DROP FOREIGN KEY \`FK_c933344d00d6b16fcf1566b5a84\``);
        await queryRunner.query(`ALTER TABLE \`Direcionamento\` DROP FOREIGN KEY \`FK_7263145c2f094b22627c24dd105\``);
        await queryRunner.query(`ALTER TABLE \`Direcionamento\` DROP FOREIGN KEY \`FK_85c3689ba2fc5ef327b0a868ad0\``);
        await queryRunner.query(`ALTER TABLE \`Acao\` DROP FOREIGN KEY \`FK_81d8aaa180f951427e6f7a53c44\``);
        await queryRunner.query(`ALTER TABLE \`Acao\` DROP FOREIGN KEY \`FK_6f6b95908be2047467f5901a39c\``);
        await queryRunner.query(`ALTER TABLE \`Acao\` DROP FOREIGN KEY \`FK_4a0c0eb22196d5e94570f8d67f8\``);
        await queryRunner.query(`ALTER TABLE \`Acao\` DROP FOREIGN KEY \`FK_c49578aa0e6a82d161af1a7bc6f\``);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` DROP FOREIGN KEY \`FK_90d296b374d2947bf494499a275\``);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` DROP FOREIGN KEY \`FK_25a50daf6603557150f59e9ef56\``);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` DROP FOREIGN KEY \`FK_94136eed977b8bc08033379c198\``);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` DROP FOREIGN KEY \`FK_d9b15735f8ff9e2510edca00bc2\``);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` DROP FOREIGN KEY \`FK_818e77e86b5018e0e480353ba8a\``);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` DROP FOREIGN KEY \`FK_30ab90c85f6a53f6f733c5b05a3\``);
        await queryRunner.query(`ALTER TABLE \`Monitor\` DROP FOREIGN KEY \`FK_34ced1e1560b9eace850e23a424\``);
        await queryRunner.query(`ALTER TABLE \`Monitor\` DROP FOREIGN KEY \`FK_88bacd5f4eade404c9f9db563f2\``);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` DROP FOREIGN KEY \`FK_fb673fb22d54f1dd99298f0773f\``);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` DROP FOREIGN KEY \`FK_46d9d6f67f5d0c5bf38cbd5099f\``);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` CHANGE \`qtdSenhasExibidasNoMonitor\` \`qtdSenhasExibidasNoMonitor\` int(2) NOT NULL COMMENT 'Quantidade de senhas exibidas no monitor de chamadas'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`Orgao_ID\` \`Orgao_ID\` int NOT NULL COMMENT 'Identificador único do órgão'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`nome\` \`nome\` varchar(45) NOT NULL COMMENT 'Nome completo do usuário'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`nivel\` \`nivel\` int NOT NULL COMMENT 'Nível de acesso: 0 - Cidadão, 1 - Administrador, 2 - Atendente, 3 - Supervisor, 4 - Editor, 5 - Gestor'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`disponibilidade\` \`disponibilidade\` tinyint NOT NULL COMMENT 'Disponibilidade para atendimento: 0 - Indisponível, 1 - Disponível' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status do usuário: 0 - Inativo, 1 - Ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do usuário'`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` CHANGE \`timestamp\` \`timestamp\` timestamp NULL COMMENT 'Data e hora do evento registrado' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` CHANGE \`codigo\` \`codigo\` varchar(45) NOT NULL COMMENT 'Código do evento de auditoria'`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` CHANGE \`senha\` \`senha\` text NOT NULL COMMENT 'Senha criptografada para segurança'`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` CHANGE \`usuario\` \`usuario\` text NOT NULL COMMENT 'Nome de usuário para autenticação'`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NOT NULL COMMENT 'ID do usuário vinculado ao login'`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` ADD CONSTRAINT \`FK_2edf88b662ccf08e1e3d23bd629\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Orgao\` CHANGE \`nome\` \`nome\` varchar(45) NOT NULL COMMENT 'Nome do órgão no sistema'`);
        await queryRunner.query(`ALTER TABLE \`Orgao\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Inativo, 1 - Ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Orgao\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do órgão'`);
        await queryRunner.query(`ALTER TABLE \`Usuario\` ADD CONSTRAINT \`FK_ac16fdcbf57da5794c6e221b44a\` FOREIGN KEY (\`Orgao_ID\`) REFERENCES \`Orgao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Servico\` CHANGE \`Orgao_ID\` \`Orgao_ID\` int NOT NULL COMMENT 'Identificador único do órgão'`);
        await queryRunner.query(`ALTER TABLE \`Servico\` CHANGE \`titulo\` \`titulo\` varchar(255) NOT NULL COMMENT 'Título descritivo do serviço'`);
        await queryRunner.query(`ALTER TABLE \`Servico\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Desativado, 1 - Disponível' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Servico\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do serviço'`);
        await queryRunner.query(`ALTER TABLE \`Servico\` ADD CONSTRAINT \`FK_41dcbbc17f020c41b5b4d1a4e23\` FOREIGN KEY (\`Orgao_ID\`) REFERENCES \`Orgao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`Local_ID\` \`Local_ID\` int NOT NULL COMMENT 'Identificador único do local'`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`Servico_ID\` \`Servico_ID\` int NOT NULL COMMENT 'Identificador único do serviço'`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`descricao\` \`descricao\` text NOT NULL COMMENT 'Descrição detalhada do serviço em HTML'`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Indisponível, 1 - Disponível' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do conteúdo'`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` ADD CONSTRAINT \`FK_595a32b60dae4f548fe15572791\` FOREIGN KEY (\`Servico_ID\`) REFERENCES \`Servico\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`Rotulo_ID\` \`Rotulo_ID\` int NOT NULL COMMENT 'Identificador único do rótulo'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`Conteudo_ID\` \`Conteudo_ID\` int NOT NULL COMMENT 'Identificador único do conteúdo'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`conteudo\` \`conteudo\` text NOT NULL COMMENT 'Conteúdo do pré-requisito em HTML'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Indisponível, 1 - Disponível' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do pré-requisito'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` ADD CONSTRAINT \`FK_153d5c9555c9e12c20a41f8075e\` FOREIGN KEY (\`Conteudo_ID\`) REFERENCES \`Conteudo\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Rotulo\` CHANGE \`rotulo\` \`rotulo\` varchar(255) NOT NULL COMMENT 'Rótulo com o título do pré-requisito para padronização de conteúdos'`);
        await queryRunner.query(`ALTER TABLE \`Rotulo\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Inativo, 1 - Ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Rotulo\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do rótulo'`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` ADD CONSTRAINT \`FK_fb733acbf5a893769678e192f55\` FOREIGN KEY (\`Rotulo_ID\`) REFERENCES \`Rotulo\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`Cidade_ID\` \`Cidade_ID\` int NOT NULL COMMENT 'Identificador único da cidade'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`SubAgregado_ID\` \`SubAgregado_ID\` int NULL COMMENT 'Identificador único do sub-agregador' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`Agregador_ID\` \`Agregador_ID\` int NULL COMMENT 'Identificador único do agregador' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`Orgao_ID\` \`Orgao_ID\` int NOT NULL COMMENT 'Identificador único do órgão'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`CEP\` \`CEP\` varchar(15) NULL COMMENT 'CEP do local de atendimento' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`telefone\` \`telefone\` text NULL COMMENT 'Telefones do local, separados por ponto e vírgula' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`linkMaps\` \`linkMaps\` text NULL COMMENT 'Link do Google Maps com a localização exata' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`endereco\` \`endereco\` text NULL COMMENT 'Endereço completo do local de atendimento' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Desativado, 1 - Ativado' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Local\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do local'`);
        await queryRunner.query(`ALTER TABLE \`Local\` ADD CONSTRAINT \`FK_43868f1ccf68d30c744e665b82a\` FOREIGN KEY (\`Orgao_ID\`) REFERENCES \`Orgao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` ADD CONSTRAINT \`FK_291c34c971b812fd3399c25c18e\` FOREIGN KEY (\`Local_ID\`) REFERENCES \`Local\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NOT NULL COMMENT 'Identificador único do usuário'`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` CHANGE \`Local_ID\` \`Local_ID\` int NOT NULL COMMENT 'Identificador único do local'`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Indisponível, 1 - Disponível' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do guichê'`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` ADD CONSTRAINT \`FK_c6b5861984a164f66f44c077a11\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` ADD CONSTRAINT \`FK_c933344d00d6b16fcf1566b5a84\` FOREIGN KEY (\`Local_ID\`) REFERENCES \`Local\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NOT NULL COMMENT 'Identificador único do usuário'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`Servico_ID\` \`Servico_ID\` int NULL COMMENT 'Identificador único do serviço' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`Guiche_ID\` \`Guiche_ID\` int NULL COMMENT 'Identificador único do guichê' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`Atendimento_ID\` \`Atendimento_ID\` int NULL COMMENT 'Identificador único do atendimento' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`anotacao\` \`anotacao\` text NULL COMMENT 'Observações registradas pelo atendente' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`horaFim\` \`horaFim\` time NULL COMMENT 'Hora de conclusão do atendimento' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`horaInicio\` \`horaInicio\` time NULL COMMENT 'Hora de início do atendimento' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`data\` \`data\` date NULL COMMENT 'Data efetiva do atendimento deste serviço' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`posicao\` \`posicao\` int NOT NULL COMMENT 'Posição do serviço na fila do atendimento'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`status\` \`status\` int NOT NULL COMMENT 'Situação: 0 - Aguardando, 1 - Em atendimento, 2 - Finalizado, 3 - Adiado' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único da ação'`);
        await queryRunner.query(`ALTER TABLE \`Acao\` ADD CONSTRAINT \`FK_81d8aaa180f951427e6f7a53c44\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Acao\` ADD CONSTRAINT \`FK_6f6b95908be2047467f5901a39c\` FOREIGN KEY (\`Servico_ID\`) REFERENCES \`Servico\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Acao\` ADD CONSTRAINT \`FK_4a0c0eb22196d5e94570f8d67f8\` FOREIGN KEY (\`Guiche_ID\`) REFERENCES \`Guiche\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`Local_ID\` \`Local_ID\` int NULL COMMENT 'Identificador único do local' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NULL COMMENT 'Identificador único do usuário' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`Cidadao_ID\` \`Cidadao_ID\` int NOT NULL COMMENT 'Identificador único do cidadão'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`dataFinal\` \`dataFinal\` timestamp NULL COMMENT 'Data de finalização do atendimento' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`dataCadastro\` \`dataCadastro\` timestamp NOT NULL COMMENT 'Data de solicitação do atendimento' DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`senha\` \`senha\` varchar(9) NOT NULL COMMENT 'Senha no formato ''LLL-000'''`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`tipo\` \`tipo\` int NOT NULL COMMENT 'Tipo: 0 - Comum, 1 - Prioridade, 2 - Retorno, 3 - Retorno com prioridade'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`status\` \`status\` int NOT NULL COMMENT 'Status: 0 - Não finalizado, 1 - Em atendimento, 2 - Finalizado, 3 - Aguardando retorno' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do atendimento'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` ADD CONSTRAINT \`FK_90d296b374d2947bf494499a275\` FOREIGN KEY (\`Local_ID\`) REFERENCES \`Local\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` ADD CONSTRAINT \`FK_25a50daf6603557150f59e9ef56\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Acao\` ADD CONSTRAINT \`FK_c49578aa0e6a82d161af1a7bc6f\` FOREIGN KEY (\`Atendimento_ID\`) REFERENCES \`Atendimento\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` CHANGE \`comentario\` \`comentario\` text NULL COMMENT 'Comentário do cidadão sobre o atendimento' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` CHANGE \`estrelas\` \`estrelas\` int(11) NOT NULL COMMENT 'Nota: 1 - Péssimo, 2 - Ruim, 3 - Razoável, 4 - Ótimo, 5 - Perfeito'`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` CHANGE \`Atendimento_ID\` \`Atendimento_ID\` int NOT NULL COMMENT 'ID do atendimento avaliado'`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` ADD CONSTRAINT \`FK_d9b15735f8ff9e2510edca00bc2\` FOREIGN KEY (\`Atendimento_ID\`) REFERENCES \`Atendimento\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`ultimoAcesso\` \`ultimoAcesso\` timestamp NULL COMMENT 'Último acesso do cidadão ao sistema' DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`dataNascimento\` \`dataNascimento\` date NULL COMMENT 'Data de nascimento do cidadão' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`prioridade\` \`prioridade\` int(11) NULL COMMENT 'Prioridade no atendimento: 1 - Idoso, 2 - Patologia' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`dataHoraCadastro\` \`dataHoraCadastro\` timestamp NOT NULL COMMENT 'Data e hora do cadastro do cidadão' DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`email\` \`email\` text NULL COMMENT 'Endereço de email do cidadão' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`telefone\` \`telefone\` text NULL COMMENT 'Telefones do cidadão, separados por ponto e vírgula' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`cidade\` \`cidade\` text NULL COMMENT 'Cidade de residência do cidadão' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Inativo, 1 - Ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`nome\` \`nome\` text NOT NULL COMMENT 'Nome completo do cidadão'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do cidadão'`);
        await queryRunner.query(`ALTER TABLE \`Atendimento\` ADD CONSTRAINT \`FK_94136eed977b8bc08033379c198\` FOREIGN KEY (\`Cidadao_ID\`) REFERENCES \`Cidadao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`Cidadao_ID\` \`Cidadao_ID\` int NULL COMMENT 'Identificador único do cidadão' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NULL COMMENT 'Identificador único do usuário' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`rotulo\` \`rotulo\` varchar(45) NOT NULL COMMENT 'Rótulo que identifica o dispositivo'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`identificacao\` \`identificacao\` varchar(45) NOT NULL COMMENT 'Chave hash que identifica o dispositivo'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Inativo, 1 - Ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do dispositivo'`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` ADD CONSTRAINT \`FK_818e77e86b5018e0e480353ba8a\` FOREIGN KEY (\`Cidadao_ID\`) REFERENCES \`Cidadao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` ADD CONSTRAINT \`FK_30ab90c85f6a53f6f733c5b05a3\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`Usuario_ID\` \`Usuario_ID\` int NOT NULL COMMENT 'Identificador único do usuário'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` DROP COLUMN \`guiches\``);
        await queryRunner.query(`ALTER TABLE \`Monitor\` ADD \`guiches\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Lista de guichês associados ao monitor (formato JSON)' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`dataCadastro\` \`dataCadastro\` timestamp NULL COMMENT 'Data de cadastro do monitor' DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`rotulo\` \`rotulo\` varchar(255) NULL COMMENT 'Rótulo para identificação do monitor' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status do monitor: 0 - Inativo, 1 - Ativo' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` CHANGE \`Dispositivo_ID\` \`Dispositivo_ID\` int NOT NULL COMMENT 'ID do dispositivo que atua como monitor de senhas'`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` ADD CONSTRAINT \`FK_88bacd5f4eade404c9f9db563f2\` FOREIGN KEY (\`Usuario_ID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` ADD CONSTRAINT \`FK_34ced1e1560b9eace850e23a424\` FOREIGN KEY (\`Dispositivo_ID\`) REFERENCES \`Dispositivo\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` CHANGE \`senha\` \`senha\` varchar(32) NOT NULL COMMENT 'Senha criptografada. Valor padrão: ''Default''' DEFAULT ''Default''`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` CHANGE \`CPF\` \`CPF\` varchar(32) NOT NULL COMMENT 'CPF formatado (ex: 123.456.789-09)'`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` CHANGE \`Cidadao_ID\` \`Cidadao_ID\` int NOT NULL COMMENT 'ID do cidadão vinculado ao login'`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` ADD CONSTRAINT \`FK_fb673fb22d54f1dd99298f0773f\` FOREIGN KEY (\`Cidadao_ID\`) REFERENCES \`Cidadao\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Cidade\` CHANGE \`Estado\` \`Estado\` text NOT NULL COMMENT 'Nome do estado onde a cidade está localizada'`);
        await queryRunner.query(`ALTER TABLE \`Cidade\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Inativa, 1 - Ativa' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Cidade\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único da cidade'`);
        await queryRunner.query(`ALTER TABLE \`Local\` ADD CONSTRAINT \`FK_333efabf632ebf13f53bf8299b0\` FOREIGN KEY (\`Cidade_ID\`) REFERENCES \`Cidade\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Agregador\` CHANGE \`nome\` \`nome\` varchar(45) NOT NULL COMMENT 'Nome do agregador de serviços'`);
        await queryRunner.query(`ALTER TABLE \`Agregador\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Desativado, 1 - Ativado' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Agregador\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do agregador'`);
        await queryRunner.query(`ALTER TABLE \`Local\` ADD CONSTRAINT \`FK_6c248ba5f55b09a1d1abf98e0a7\` FOREIGN KEY (\`Agregador_ID\`) REFERENCES \`Agregador\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` CHANGE \`Agregador_ID\` \`Agregador_ID\` int NOT NULL COMMENT 'Identificador único do agregador'`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` CHANGE \`nome\` \`nome\` text NOT NULL COMMENT 'Nome do sub-agregador de serviços'`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` CHANGE \`status\` \`status\` tinyint NOT NULL COMMENT 'Status: 0 - Desativado, 1 - Ativado' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` CHANGE \`ID\` \`ID\` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do sub-agregador'`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` ADD CONSTRAINT \`FK_46d9d6f67f5d0c5bf38cbd5099f\` FOREIGN KEY (\`Agregador_ID\`) REFERENCES \`Agregador\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Local\` ADD CONSTRAINT \`FK_ce835d1dc03811939b677a4d1f1\` FOREIGN KEY (\`SubAgregado_ID\`) REFERENCES \`SubAgregado\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` DROP COLUMN \`Usuario_ID\``);
        await queryRunner.query(`ALTER TABLE \`Guiche\` DROP COLUMN \`disponibilidade\``);
        await queryRunner.query(`ALTER TABLE \`Guiche\` DROP COLUMN \`identificacao\``);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` DROP COLUMN \`Auth0\``);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` ADD \`ID\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` ADD PRIMARY KEY (\`ID\`)`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` ADD \`usuarioRefID\` int NOT NULL COMMENT 'Identificador único do usuário'`);
        await queryRunner.query(`ALTER TABLE \`Servico\` ADD \`identificacao\` varchar(5) NOT NULL COMMENT 'Identificação do serviço para composição de senhas'`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` ADD \`numero\` int(3) NOT NULL COMMENT 'Número do guichê (formato 000)'`);
        await queryRunner.query(`ALTER TABLE \`Cidadao\` ADD \`auth0\` text NULL COMMENT 'Dados de autenticação via Google ou Facebook (formato JSON)' DEFAULT 'NULL'`);
        await queryRunner.query(`DROP TABLE \`Direcionamento\``);
        await queryRunner.query(`ALTER TABLE \`Configuracoes\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`LoginUsuario\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Conteudo\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Requisito\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Rotulo\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Local\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Guiche\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Acao\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Avaliacao\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Dispositivo\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Monitor\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`LoginCidadao\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Cidade\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Agregador\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`SubAgregado\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`Cidade\` CHANGE \`Estado\` \`estado\` text NOT NULL COMMENT 'Nome do estado onde a cidade está localizada'`);
        await queryRunner.query(`ALTER TABLE \`Auditoria\` ADD CONSTRAINT \`FK_1f4e9039fc5f64667e4693d2742\` FOREIGN KEY (\`usuarioRefID\`) REFERENCES \`Usuario\`(\`ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
